#!/bin/bash

set -e

# Update OS
apt update -y

# Install prerequisites
apt install -y ca-certificates curl

# Add Docker GPG Key
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

# Add Docker Repository
cat > /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/ubuntu
Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
Components: stable
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/docker.asc
EOF

# Update package index
apt update -y

# Install Docker
apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Enable Docker
systemctl enable docker
systemctl start docker

# Add ubuntu user to docker group
usermod -aG docker ubuntu

# Pull and run SonarQube
docker pull sonarqube:10.6-community

docker run -d \
  --name sonarqube-custom \
  --restart unless-stopped \
  -p 9000:9000 \
  sonarqube:10.6-community

# Log versions
docker --version > /var/log/docker-version.log
docker compose version >> /var/log/docker-version.log

echo "Docker and SonarQube installation completed" > /var/log/user-data-success.log

## One-Liner Cleanup ##

docker stop sonarqube-custom 2>/dev/null || true
docker rm sonarqube-custom 2>/dev/null || true
sudo systemctl stop docker
sudo apt remove -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo apt autoremove -y
sudo rm -rf /var/lib/docker /var/lib/containerd
sudo rm -f /etc/apt/sources.list.d/docker.sources /etc/apt/keyrings/docker.asc
